# Generated by Django 5.0.6 on 2024-07-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularcourse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='popularcourse',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='popularcourse',
            name='instructor',
        ),
        migrations.AddField(
            model_name='popularcourse',
            name='number_of_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='popularcourse',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='popularcourse',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=0),
        ),
        migrations.AddField(
            model_name='popularcourse',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
