# Generated by Django 5.0.6 on 2024-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_teacher_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='social_media',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
