# Generated by Django 5.0.6 on 2024-07-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
