# Generated by Django 5.0.6 on 2024-07-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_course_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url_name',
            field=models.CharField(blank=True, choices=[('web_design', 'Web Design'), ('development', 'Development'), ('seo', 'SEO'), ('game_design', 'Game Design')], max_length=50, null=True),
        ),
    ]
