# Generated by Django 5.0.6 on 2024-07-31 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.bloglist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_possible',
            field=models.BooleanField(default=False),
        ),
    ]
