# Generated by Django 5.0.6 on 2024-07-31 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_comment_blog_list_comment_is_possible'),
        ('courses', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='blogs/')),
            ],
        ),
        migrations.AddField(
            model_name='bloglist',
            name='course',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='courses.category'),
            preserve_default=False,
        ),
    ]
