# Generated by Django 5.0.6 on 2024-07-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], default='Middle'),
        ),
    ]
